---
uglyurls: true
theme: hugo-bootstrap-doc
params:
  project_name: Lighthouse
  project_tagline: Library for runtime system discovery
  github_host: github.com
  github_repository: getnelson/lighthouse
  travis_url: https://travis-ci.org/getnelson/lighthouse
  license: Copyright Verizon 2015-2016
  license_url: https://en.wikipedia.org/wiki/All_rights_reserved
  version: 3.0.x
  google_analytics: UA-57263411-7
  header:
    color: green
    trianglify: true
  header_links:
    - title: GitHub
      url: https://github.com/getnelson/lighthouse
    - title: API Docs
      url: https://getnelson.github.io/lighthouse/api/
  footer_links:
    - title: GitHub
      url: https://github.com/getnelson/lighthouse
    - title: Issues
      url: https://github.com/getnelson/lighthouse/issues
